#pragma config(Sensor, in1,    front_line,     sensorLineFollower)
#pragma config(Sensor, in2,    back_line,      sensorLineFollower)
#pragma config(Sensor, in3,    light,          sensorReflection)
#pragma config(Sensor, dgtl1,  right_sonar,    sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  left_sonar,     sensorSONAR_cm)
#pragma config(Sensor, dgtl5,  encoder_in,     sensorQuadEncoder)
#pragma config(Motor,  port7,           right_motor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           servo,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           left_motor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const speed = 63; // The default speed to be used throughout the program

void forward(int speed){
	// A simple function to simplify the act of moving forward
	motor[right_motor] = speed; 
	motor[left_motor] = speed;
}

void back(int speed){
	// A function to make going backward more simple
	motor[right_motor] = speed * -1;
	Motor[left_motor] = speed * -1;
}

void stop(){
	// A function to stop both motors
	motor[right_motor] = 0;
	motor[left_motor] = 0;
}

void turn_right() {
	// A function to turn the robot to the right
	motor[right_motor] = -63;
	motor[left_motor] = 63;
	wait1Msec(750);
}

void turn_left() {
	// A function to turn the robot to the left using a point turn
	motor[right_motor] = 63;
	motor[left_motor] = -63;
	wait1Msec(750);
}

void extinguish() {
	/** A function that moves the robot forward with the intent of placing the balloon over top
	 *  of the candle
	 */
	forward(63);
	wait1Msec(200);
	stop();
	wait1Msec(3000); // Wait 3 seconds to hopefully extinguish the fire
	back(63);	 // Move back to the original position
	wait1Msec(200);
}

void rotate_arm() {
	// A function to rotate the arm to put the second balloon into place, if necessary
	while(SensorValue[encoder] != 45) { 	// Wait for the servo to turn 45 degrees
		motor[servo] = 63;		// Have the servo spinning while checking the encoder
	}
	motor[servo] = 0;			// Stop the servo
}

void rotate() {
	// A function to rotate the robot a small amount in order to scan the room
	motor[right_motor] = 63;	//set the motor powers to the default speed;
	motor[left_motor] = -63;
	wait1Msec(100);
}


void room_scan() {
	forward(63);
	wait1Msec(1000);
	while(fire == false) {
		int counter = 0;
		if(SensorValue[light] >= 20 && counter < 29) {
			rotate();
			counter += 1;
		} else {
			extinguish();
			if(SensorValue[light] <= 20) {
				rotate_arm();
				extinguish();
			} else {
				return;
			}
		}
	}
}

task main()
{
	wait1Msec(1000);
	bMotorReflected[right_motor] = true;
	forward(63);
	while(SensorValue[right_sonar] <= 15) {
		forward(63);
	}
	turn_right();
	while(SensorValue[back_line] >= 100) { // while sensor sees black
		forward(63);
		// untilSonarGreaterThan(15, right_sonar);
		while(SensorValue[right_sonar] <= 15) {
			forward(63);
		}
		turn_right();
		forward(63);
		while(SensorValue[back_line] <= 100) {
			forward();
			if(SensorValue[back_line] >= 100) {
				stop();
				room_scan();
			}
		}
	}
	forward(63);
	wait1Msec(1000);
	turn_left();
	while(SensorValue[left_sonar] <= 15) {
		forward(63);
	}
	turn_right();
	while(SensorValue[right_sonar] <=15) {
		forward();
	}
	turn_right();
	room_scan();
	forward(63);
	wait1Msec(1000);
	turn_left();
	while(SensorValue[right_sonar] <= 15) {
		forward(63);	
	}
	turn_right();
	room_scan();
	forward(63);
	wait1Msec(1000);
	turn_right();
	while(SensorValue[right_sonar] <= 15) {
		forward(63);
	}
	turn_right();
	while(SensorValue[left_sonar] <= 15) {
		forward(63);
	}
	turn_left();
	room_scan();
	forward(63);
	wait1Msec(1000);
	turn_right();
	while(SensorValue[right_sonar] <= 15){
		forward(63);
	}
	turn_right();
	while(SensorValue[right_sonar] <= 15) {
		forward(63);
	}
	stop();
}
